### ISSUE TITLE
Missing `scripts/data_preparation/`

### ISSUE THREAD

**Issue by hiraksarkar** [theislab/ncem_benchmarks#1]
Hi, 

I am not able to find the directory `data_preparation` as described in README. It would be really helpful if it can be added.

Thanks

**Comment by AnnaChristina** [comment]
Hi @hiraksarkar ,

thanks for mentioning! Please find the directory for data preparation [here](https://github.com/theislab/ncem_benchmarks/tree/main/notebooks/data_preparation).

I added the respective notebook for the [MERFISH - brain dataset](https://github.com/theislab/ncem_benchmarks/blob/main/notebooks/data_preparation/data_preparation_merfish_brain.ipynb). 

We moved data preparation to notebooks, as this is currently only required for the MERFISH - brain dataset. For the remaining datasets no preprocessing was applied. Happy to link you to the original datasets or assist further if needed.

**Comment by hiraksarkar** [comment]
I left a comment on the Merfish dataset front in the tutorial issue (It seems without the CSV we can not run NCEM unfortunately). For other datasets it's not entirely clear to me which files should be downloaded and how to provide them to NCEM. Apologies if there is already a tutorial that I have missed. 

For example, in  case of "CODEX cancer" data, the actual [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7479520/) leads to a dataset [directory](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=70227790). It contains around 2 TB of processed images. Should I download that ? Given that directory I am not sure how do I call NCEM on that. The merfish data should be more straightforward given I can obtain the `metadata.csv` file.

Thanks

**Comment by AnnaChristina** [comment]
Hi @hiraksarkar, I added more detailed instructions to the README of [ncem_tutorials](https://github.com/theislab/ncem_tutorials) and [ncem_benchmarks](https://github.com/theislab/ncem_benchmarks) on how to access the public datasets.

For the CODEX cancer dataset, only the single-cell data is required to test ncem, which is stored in a different [directory](https://data.mendeley.com/datasets/mpjzbtfgfr/1) with 213 MB. So no need to download the 2TB of images. 

To run tutorials or data exploration, simply store the files in a directory of your choice and adjust the `datadir` in the respective notebooks. We stored datasets in folders named by first author. If you follow a different convention, also adjust `data_path` whenever ncem's `get_data` function is called. 

Thanks for your comments, we are still enhancing the usability of ncem, so any feedback if highly appreciated.

**Comment by hiraksarkar** [comment]
Hi @AnnaChristina amazing, really appreciate the help, trying this now. I have some questions about the manuscript, should I just email them if that's possible. 
Again, thanks a lot for helping.

**Comment by AnnaChristina** [comment]
Sure! Please feel free to raise additional issues whenever needed. Yes, just email me and @davidsebfischer. Happy to discuss and answer!

**Comment by hiraksarkar** [comment]
Hi @AnnaChristina ,

Just wanna mention the dataloader assumes `scMEP_MIBI_singlecell.csv` is inside a directory `scMEP_MIBI_singlecell` and not the zipped file. 

Except that it is working fine, although I am using same variable values as mentioned for Zheng tutorial.

**Comment by AnnaChristina** [comment]
Hi @hiraksarkar, 

Yes. The dataloader expects certain folder structures.  We will enhance this in the future. 

Great. You can basically run the tutorial for each dataset with similar parameters. For more explanation on how to set specific parameters (e.g. radius), you can check the data exploration notebooks and the manuscript.
