### ISSUE TITLE
Cannot find cell_metadata.csv for MERFISH brain data.

### ISSUE THREAD

**Issue by JINJINT** [theislab/ncem_benchmarks#4]
Hi,

I am trying to reproduce results for the **MERFISH brain data** using **merfish_brain.ipynb**, but i cannot find the file **cell_metadata.csv** anywhere in the public data source https://download.brainimagelibrary.org/cf/1c/cf1c1a431ef8d021/.

Could you tell me how you got this data? Many thanks!

Best,
Jinjin

**Comment by AnnaChristina** [comment]
We reached out to the authors of this dataset directly and they provided us the metadata for the data mentioned in their manuscript. The data format might be slightly different according to the public data source, but we basically used a table specifying the different annotation levels and the calculated segmentation centers. I hope this answers your question.
